# Generated by Django 4.2.7 on 2023-12-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0002_popularproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('list_data', models.JSONField()),
                ('author', models.CharField(max_length=255)),
                ('images', models.JSONField()),
            ],
        ),
    ]
