# Generated by Django 4.2.7 on 2023-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0003_projectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedProductModel',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('list_data', models.JSONField()),
                ('author', models.CharField(max_length=255)),
                ('images', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
