# Generated by Django 4.2.7 on 2023-12-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0004_detailedproductmodel_delete_projectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiliacUser',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pfp', models.CharField(max_length=255)),
            ],
        ),
    ]
