# Generated by Django 4.2.7 on 2024-01-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0005_liliacuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LiliacUser',
        ),
    ]
