# Generated by Django 4.2.7 on 2024-01-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0007_customuser_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='other_ids',
            field=models.ManyToManyField(blank=True, related_name='related_users', to='web_backend.customuser'),
        ),
    ]
