# Generated by Django 4.2.7 on 2024-01-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0009_remove_customuser_other_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedproductmodel',
            name='list_data',
        ),
    ]
