# Generated by Django 4.2.7 on 2024-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0010_remove_detailedproductmodel_list_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_products_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_products',
            field=models.ManyToManyField(blank=True, related_name='creators', to='web_backend.detailedproductmodel'),
        ),
    ]
