# Generated by Django 4.2.7 on 2024-01-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0012_remove_customuser_created_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedproductmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
