# Generated by Django 4.2.7 on 2024-01-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0013_alter_detailedproductmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLists',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('favorite', models.JSONField(blank=True, null=True)),
                ('friends', models.JSONField(blank=True, null=True)),
                ('cart', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
